### ISSUE TITLE
Simple example analogous to string_view

### ISSUE THREAD

**Issue by parcollet** [mgehre/clang#46] opened 2019-05-22 02:25 UTC
Hi,
I am trying the version at godbolt.org.
As expected, -Wlifetime  detects the dangling pointer in the following code 
```
#include <string>

std::string_view g() {
    std::string s="dangling";
    return s;
}
```

but it does not detect a simple dangling array_view (cf https://godbolt.org/z/O6rFgP)

```
struct array{
   double *data;
   array(): data(new double[10]){}
   ~array() { delete[] data;}
};

struct array_view { 
   double * data;
   array_view(array& a) : data(a.data){}
};

array_view f() { 
    array a;
    return a;
}
```

Am I missing something ?

clang version 9.0.0 (https://github.com/mgehre/clang e3b18a33a4df1e183d2c5e4c816db16abcb868e0) (https://github.com/llvm-mirror/llvm 75521639735cfda147aadecacb91968d8f92e3dd)

**Comment by mgehre** [comment] 2019-05-31 20:56
In your example, array_view is categorized as Value and not as Pointer, see https://godbolt.org/z/Z0Uv5o.
There are various heuristics around detecting type categories, but you can also annotate them explicitly with [[gsl::Owner(DerefType)]]

**Comment by Xazax-hun** [comment] 2019-06-26 17:19
I will close this issue for now. This is the intended behavior when no explicit annotations are added.

**Closed by Xazax-hun** 2019-06-26 17:19 UTC
