### ISSUE TITLE
Handling non-range-for loop iterations

### ISSUE THREAD

**Issue by roccomoretti** [mgehre/clang#39] opened 2018-12-06 17:02 UTC
A common cause of (what I believe to be false positives) when the tool is applied to our code base is the iterator-style for loops:

    #include <vector>
    
    void fun() {
      std::vector<int> myvector;
      for ( std::vector<int>::const_iterator iter = myvector.begin(), end = myvector.end();
        iter != end;
        ++iter )
      {}
    }

yields the following -Wlifetime issues:

    loop.cc:6:5: warning: passing a dangling pointer as argument [-Wlifetime]
        iter != end;
        ^
    loop.cc:5:64: note: temporary was destroyed at the end of the full expression
      for ( std::vector<int>::const_iterator iter = myvector.begin(), end = myvector.end();
                                                                   ^
    loop.cc:6:13: warning: passing a dangling pointer as argument [-Wlifetime]
        iter != end;
                ^
    loop.cc:5:86: note: temporary was destroyed at the end of the full expression
      for ( std::vector<int>::const_iterator iter = myvector.begin(), end = myvector.end();
                                                                                         ^
    loop.cc:7:7: warning: passing a dangling pointer as argument [-Wlifetime]
        ++iter )
          ^
    loop.cc:5:64: note: temporary was destroyed at the end of the full expression
      for ( std::vector<int>::const_iterator iter = myvector.begin(), end = myvector.end();
                                                                   ^
    3 warnings generated.

I realize that this particular case would be better with a range-for, but there are other cases of iterator for loops which don't map so cleanly (iterator advancement in the body, simultaneous iteration across multiple vectors, etc.) -- This is just a simple demonstration example. 

`llvm: d8e175bca5919de13fe003cab6b10f23af3d055d`
`clang: 4385bf94e655affaf1555bfbde3ccbb5c16c3ee8`

**Comment by roccomoretti** [comment] 2018-12-06 17:18
Is this perhaps a side effect of the precise loop unrolling rule specified in the whitepaper?

`for(/*init*/;/*cond*/;/*incr*/){/*body*/}` -> 
`if(/*init*/;/*cond*/){/*body*/;/*incr*/}if(/*cond*/){/*body*/}`

I'm wondering if that has a slight difference in semantics with respect to the lifetime of objects defined in the `/*init*/`. Would `if(/*init*/;/*cond*/){/*body*/;/*incr*/;if(/*cond*/){/*body*/}}` be a more appropriate translation?

**Comment by mheistermann** [comment] 2019-05-29 16:35
I also encountered this false positive, and experimented a bit.
I believe it is related to the conversion from` vector<>::iterator` to `const_iterator` and unrelated to the loop.

Using either `auto` or `vector<>::iterator` for the type or `cbegin()`/`cend()` works around this issue.

**Comment by Xazax-hun** [comment] 2019-06-26 17:47
I started to look into this issue. Indeed, the problem is the iterator -> const iterator conversion. In case the conversion constructor takes its argument by value it works as intended, but in most STL implementations it is taken by a const reference. Thus, the analysis will think that the const_iterator actually points to the iterator rather than the vector. I might look into fixing this soon.

**Comment by Xazax-hun** [comment] 2019-06-26 18:18
Should be fixed in: https://github.com/mgehre/clang/commit/487613547eb19a8c1e5a9f4b89aa10c246a3fd63

Thank you for reporting!

**Closed by Xazax-hun** 2019-06-26 18:18 UTC
